import type { SmartRoomTypeDefinition } from "./editor-types";
import { DEVICE_ENTITY_PLACEHOLDER, EXTRA_FIELD_PLACEHOLDERS } from "./editor-types";

export const BUILTIN_TYPE_DEFINITIONS: SmartRoomTypeDefinition[] = [
  {
    id: "light",
    label: "Light",
    icon: "mdi:lightbulb",
    editor_color: "#f5c84c",
    entity_required: true,
    allowed_main_entities: ["light.", "switch."],
    restrict_to_room_area: false,
    default_device: {
      entity: DEVICE_ENTITY_PLACEHOLDER,
      type: "light",
      image_on: "light_on.png",
      image_off: "light_off.png",
      tap_action: { action: "button", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      hold_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      offline: {
        enabled: true,
        strike: true,
        dim_opacity: 0.5,
        conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
      },
      states: {
        on_conditions: [],
        alert_conditions: [],
        states: [{
          name: "On",
          enabled: true,
          text: "",
          outlined: true,
          border_color: "yellow",
          icon_active: "",
          icon_inactive: "",
          icon_active_color: "yellow",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "eq", value: "on" }],
          header_badge_active: "light",
          count_light: true,
          count_media: false,
          count_rec: false,
          preset: true,
          preset_source: "type",
        },{
          name: "Offline",
          enabled: true,
          text: "",
          outlined: false,
          border_color: "white",
          icon_active: "",
          icon_inactive: "",
          icon_active_color: "white",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
          header_badge: "none",
          count_light: false,
          count_media: false,
          count_rec: false,
          preset: true,
          preset_source: "offline",
        }],
        alerts: [],
      },
    },
  },
  {
    id: "camera",
    label: "Camera",
    icon: "mdi:cctv",
    editor_color: "#ff6b6b",
    entity_required: true,
    allowed_main_entities: ["camera."],
    restrict_to_room_area: false,
    extra_fields: [{ key: "privacy", label: "Privacy entity", hint: "Optional. Adds the eye-off preset state when valid.", selector_domains: ["switch.", "input_boolean."] }],
    default_device: {
      entity: DEVICE_ENTITY_PLACEHOLDER,
      type: "camera",
      image: "camera_default.png",
      tap_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      hold_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      offline: {
        enabled: true,
        strike: true,
        dim_opacity: 0.5,
        conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
      },
      states: {
        on_conditions: [],
        alert_conditions: [],
        states: [
          {
            name: "Live",
            enabled: true,
            text: "",
            outlined: false,
            border_color: "green",
            icon_active: "mdi:record-rec",
            icon_inactive: "",
            icon_active_color: "green",
            icon_inactive_color: "white",
            image_active: "",
            image_inactive: "",
            conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "eq", value: "idle" }],
            header_badge_active: "rec",
            count_light: false,
            count_media: false,
            count_rec: true,
            preset: true,
            preset_source: "camera_live",
          },
          {
            name: "Privacy",
            enabled: true,
            text: "",
            outlined: false,
            border_color: "white",
            icon_active: "mdi:eye-off",
            icon_inactive: "",
            icon_active_color: "white",
            icon_inactive_color: "white",
            image_active: "",
            image_inactive: "",
            conditions: [{ entity: EXTRA_FIELD_PLACEHOLDERS.privacy, operator: "eq", value: "on" }],
            count_light: false,
            count_media: false,
            count_rec: false,
            preset: true,
            preset_source: "camera_privacy",
          },
          {
            name: "Offline",
            enabled: true,
            text: "",
            outlined: false,
            border_color: "white",
            icon_active: "",
            icon_inactive: "",
            icon_active_color: "white",
            icon_inactive_color: "white",
            image_active: "",
            image_inactive: "",
            conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
            header_badge: "none",
            count_light: false,
            count_media: false,
            count_rec: false,
            preset: true,
            preset_source: "offline",
          },
        ],
        alerts: [],
      },
    },
  },
  {
    id: "media_player",
    label: "Media player",
    icon: "mdi:play-box",
    editor_color: "#d7dde6",
    entity_required: true,
    allowed_main_entities: ["media_player."],
    restrict_to_room_area: false,
    default_device: {
      entity: DEVICE_ENTITY_PLACEHOLDER,
      type: "media_player",
      image: "media_player_default.png",
      tap_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      hold_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      offline: {
        enabled: true,
        strike: true,
        dim_opacity: 0.5,
        conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
      },
      states: {
        on_conditions: [],
        alert_conditions: [],
        states: [{
          name: "Playing",
          enabled: true,
          text: "",
          outlined: true,
          border_color: "white",
          icon_active: "",
          icon_inactive: "",
          icon_active_color: "white",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["on", "playing", "paused", "buffering"] }],
          header_badge_active: "playing",
          count_light: false,
          count_media: true,
          count_rec: false,
          preset: true,
          preset_source: "type",
        },{
          name: "Offline",
          enabled: true,
          text: "",
          outlined: false,
          border_color: "white",
          icon_active: "",
          icon_inactive: "",
          icon_active_color: "white",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
          header_badge: "none",
          count_light: false,
          count_media: false,
          count_rec: false,
          preset: true,
          preset_source: "offline",
        }],
        alerts: [],
      },
    },
  },
  {
    id: "lock",
    label: "Lock",
    icon: "mdi:lock",
    editor_color: "#ff9f43",
    entity_required: true,
    allowed_main_entities: ["lock."],
    restrict_to_room_area: false,
    default_device: {
      entity: DEVICE_ENTITY_PLACEHOLDER,
      type: "lock",
      image: "lock_default.png",
      tap_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      hold_action: { action: "more-info", entity: DEVICE_ENTITY_PLACEHOLDER, preset: true },
      offline: {
        enabled: true,
        strike: true,
        dim_opacity: 0.5,
        conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
      },
      states: {
        on_conditions: [],
        alert_conditions: [],
        states: [{
          name: "Unlocked",
          enabled: true,
          text: "",
          outlined: false,
          border_color: "red",
          icon_active: "mdi:lock-open-variant",
          icon_inactive: "mdi:lock",
          icon_active_color: "red",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "neq", value: "locked" }],
          count_light: false,
          count_media: false,
          count_rec: false,
          preset: true,
          preset_source: "type",
        },{
          name: "Offline",
          enabled: true,
          text: "",
          outlined: false,
          border_color: "white",
          icon_active: "",
          icon_inactive: "",
          icon_active_color: "white",
          icon_inactive_color: "white",
          image_active: "",
          image_inactive: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "in", value: ["unavailable", "unknown"] }],
          header_badge: "none",
          count_light: false,
          count_media: false,
          count_rec: false,
          preset: true,
          preset_source: "offline",
        }],
        alerts: [{
          name: "Unlocked alert",
          enabled: true,
          message: "",
          conditions: [{ entity: DEVICE_ENTITY_PLACEHOLDER, operator: "neq", value: "locked" }],
          outlined: true,
          border_color: "red",
          icon: "mdi:lock-open-variant",
          icon_color: "red",
          header_badge: "lock_open",
          preset: true,
          preset_source: "type",
        }],
      },
    },
  },
  {
    id: "custom",
    label: "Custom",
    icon: "mdi:circle-outline",
    editor_color: "#4cc9f0",
    entity_required: false,
    allowed_main_entities: ["*"],
    restrict_to_room_area: false,
    default_device: {
      entity: "",
      type: "custom",
      image: "custom_default.png",
      states: { on_conditions: [], alert_conditions: [], states: [], alerts: [] },
    },
  },
];
