export const INITIAL_STATES = ["closed", "open", "conditional"] as const;
export const OPERATORS = ["eq", "neq", "gt", "gte", "lt", "lte", "in", "not_in"] as const;
export const COLOR_OPTIONS = [
  { value: "white", label: "White", swatch: "#ffffff" },
  { value: "green", label: "Green", swatch: "#34c759" },
  { value: "red", label: "Red", swatch: "#ff3b30" },
  { value: "yellow", label: "Yellow", swatch: "#ffd700" },
  { value: "blue", label: "Blue", swatch: "#3b82f6" },
  { value: "orange", label: "Orange", swatch: "#ff9f43" },
  { value: "cyan", label: "Cyan", swatch: "#4cc9f0" },
  { value: "purple", label: "Purple", swatch: "#8b5cf6" },
  { value: "gray", label: "Gray", swatch: "#94a3b8" },
] as const;
export const ALERT_HEADER_BADGE_OPTIONS = [
  { value: "alert_generic", label: "Generic alert", icon: "mdi:alert-circle-outline" },
  { value: "low_battery", label: "Low battery", icon: "mdi:battery-alert-variant-outline" },
  { value: "fire", label: "Fire alarm", icon: "mdi:fire-alert" },
  { value: "water", label: "Water alarm", icon: "mdi:water-alert" },
  { value: "lock_open", label: "Lock open", icon: "mdi:lock-open-variant" },
  { value: "door_open", label: "Door open", icon: "mdi:door-open" },
  { value: "plug_off", label: "Disconnected plug", icon: "mdi:power-plug-off-outline" },
] as const;

export const HEADER_BADGE_OPTIONS = [
  { value: "none", label: "None", icon: "" },
  { value: "light", label: "Light", icon: "mdi:lightbulb", color: "#ffd700" },
  { value: "playing", label: "Playing", icon: "mdi:play", color: "#ffffff" },
  { value: "rec", label: "REC", icon: "mdi:record-rec", color: "#ff3b30" },
  { value: "door_open", label: "Door open", icon: "mdi:door-open", color: "#ff9f43" },
  { value: "door_closed", label: "Door closed", icon: "mdi:door-closed", color: "#34c759" },
  { value: "lock_open", label: "Lock open", icon: "mdi:lock-open-variant", color: "#ff3b30" },
  { value: "lock_closed", label: "Lock closed", icon: "mdi:lock", color: "#34c759" },
  { value: "presence", label: "Presence", icon: "mdi:account", color: "#ffffff" },
  { value: "fire", label: "Fire alarm", icon: "mdi:fire-alert", color: "#ff3b30" },
  { value: "water", label: "Water alarm", icon: "mdi:water-alert", color: "#ff3b30" },
  { value: "plug_off", label: "Disconnected plug", icon: "mdi:power-plug-off-outline", color: "#ffffff" },
  { value: "low_battery", label: "Low battery", icon: "mdi:battery-alert-variant-outline", color: "#ff3b30" },
  { value: "automation", label: "Automation", icon: "mdi:robot", color: "#ffffff" },
] as const;
export const MAIN_ENTITY_DOMAIN_OPTIONS = [
  { value: "*", label: "Any entity" },
  { value: "light.", label: "light" },
  { value: "switch.", label: "switch" },
  { value: "camera.", label: "camera" },
  { value: "media_player.", label: "media_player" },
  { value: "lock.", label: "lock" },
  { value: "binary_sensor.", label: "binary_sensor" },
  { value: "sensor.", label: "sensor" },
  { value: "fan.", label: "fan" },
  { value: "cover.", label: "cover" },
  { value: "climate.", label: "climate" },
  { value: "vacuum.", label: "vacuum" },
  { value: "alarm_control_panel.", label: "alarm_control_panel" },
  { value: "person.", label: "person" },
  { value: "device_tracker.", label: "device_tracker" },
  { value: "button.", label: "button" },
  { value: "scene.", label: "scene" },
  { value: "script.", label: "script" },
  { value: "input_boolean.", label: "input_boolean" },
  { value: "input_select.", label: "input_select" },
  { value: "input_button.", label: "input_button" },
  { value: "number.", label: "number" },
  { value: "select.", label: "select" },
  { value: "remote.", label: "remote" },
  { value: "update.", label: "update" },
  { value: "humidifier.", label: "humidifier" },
  { value: "water_heater.", label: "water_heater" },
  { value: "timer.", label: "timer" },
  { value: "valve.", label: "valve" },
  { value: "siren.", label: "siren" },
  { value: "tts.", label: "tts" },
  { value: "weather.", label: "weather" },
  { value: "sun.", label: "sun" },
  { value: "zone.", label: "zone" },
  { value: "automation.", label: "automation" },
] as const;
export const DOMAIN_MULTISELECT_OPTIONS = [
  { value: "*", label: "Any domains" },
  ...MAIN_ENTITY_DOMAIN_OPTIONS
    .filter((item) => item.value !== "*")
    .map((item) => ({ value: item.value, label: item.label })),
] as const;
